Simplifies Docker images

diff --git a/images/php/5.6/Dockerfile b/images/php/5.6/Dockerfile
--- a/images/php/5.6/Dockerfile
+++ b/images/php/5.6/Dockerfile
@@ -1,50 +1,51 @@
-FROM php:7.0-fpm-jessie
+FROM php:5.6-fpm
 
 LABEL maintainer="Max Carvalho <max.carvalho@cloverbox.com.br>"
 
-# Gosu
-ENV GOSU_VERSION 1.10
-RUN set -x \
-    && apt-get update && apt-get install -y --no-install-recommends ca-certificates wget rsync && rm -rf /var/lib/apt/lists/* \
-    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
-    && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
-    && export GNUPGHOME="$(mktemp -d)" \
-    && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
-    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
-    && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
-    && chmod +x /usr/local/bin/gosu \
-    && gosu nobody true
-
 # Global
-RUN apt-get update -qq && apt-get install -y --no-install-recommends curl git pv mysql-client wget unzip zip \
+RUN apt-get update -qq && apt-get install -y --no-install-recommends gosu curl git pv mysql-client wget unzip zip \
     openssh-server unzip vim
 
 # PHP
 ENV DEV_LIBS libfreetype6-dev libjpeg62-turbo-dev libpng12-dev libgd-dev libmagickwand-dev libc-client-dev libkrb5-dev \
-    libicu-dev libldap2-dev libmcrypt-dev openssl unixodbc-dev libxml2-dev freetds-dev libssl-dev libpspell-dev libtidy-dev \
-    libxslt-dev libmemcached-dev
+    libicu-dev libldap2-dev libmcrypt-dev openssl unixodbc-dev libxml2-dev freetds-dev libssl-dev libpspell-dev \
+    libtidy-dev libxslt-dev libmemcached-dev
 RUN apt-get install -y --no-install-recommends $DEV_LIBS \
-    && pecl install igbinary && pecl install imagick && pecl install && pecl install redis && pecl install memcached \
-    && pecl install xdebug && pecl install lzf \
+    && pecl install igbinary && pecl install imagick && pecl install redis \
+    && pecl install memcached-2.2.0.tgz && pecl install xdebug-2.5.5.tgz && pecl install lzf && pecl install memcache \
     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
     && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
     && docker-php-ext-configure intl \
     && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
     && docker-php-ext-configure pdo_dblib --with-libdir=/lib/x86_64-linux-gnu \
     && docker-php-ext-install -j$(nproc) bcmath calendar exif gd gettext imap intl ldap mcrypt mysqli pcntl pdo_dblib \
-        pdo_mysql pspell shmop soap sockets sysvmsg sysvsem sysvshm tidy wddx xmlrpc xsl zip opcache \
+    pdo_mysql pspell shmop soap sockets sysvmsg sysvsem sysvshm tidy wddx xmlrpc xsl zip opcache \
     && git clone --recursive --depth=1 https://github.com/kjdev/php-ext-snappy.git && cd php-ext-snappy \
     && phpize && ./configure && make && make install \
-    && docker-php-ext-enable igbinary imagick redis snappy memcached \
-    && curl -sSL -o php7.zip https://github.com/websupport-sk/pecl-memcache/archive/php7.zip \
-    && unzip php7 && cd pecl-memcache-php7 && /usr/local/bin/phpize \
-    && ./configure --with-php-config=/usr/local/bin/php-config && make && make install \
-    && echo "extension=memcache.so" > /usr/local/etc/php/conf.d/ext-memcache.ini \
+    && docker-php-ext-enable igbinary imagick redis snappy memcache memcached \
     && echo "extension=lzf.so" > /usr/local/etc/php/conf.d/ext-lzfs.ini \
-    && rm -rf /tmp/pecl-memcache-php7 php7.zip php-ext-snappy \
+    && rm -rf php-ext-snappy \
     && php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/local/bin/ --filename=composer \
     && curl -O https://files.magerun.net/n98-magerun.phar && mv n98-magerun.phar /usr/bin/magerun && chmod +x /usr/bin/magerun \
     && mkdir -p /usr/local/var/log && touch /usr/local/var/log/php-fpm.log && chmod 777 /usr/local/var/log/php-fpm.log
+
+# Composer
+ENV COMPOSER_ALLOW_SUPERUSER 1
+ENV COMPOSER_HOME /tmp
+ENV COMPOSER_VERSION 1.7.2
+
+RUN export EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"; \
+    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"; \
+    export ACTUAL_SIGNATURE="$(php -r "echo hash_file('SHA384', 'composer-setup.php');")"; \
+    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then \
+        >&2 echo 'ERROR: Invalid installer signature'; \
+        rm composer-setup.php; \
+        exit 1; \
+    fi; \
+    php composer-setup.php --quiet --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION}; \
+    RESULT=$?; \
+    rm composer-setup.php; \
+    echo ${RESULT}
 
 RUN set -ex \
     && cd /usr/local/etc \
@@ -59,8 +60,6 @@ RUN apt-get -y autoremove && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*
 
 RUN mkdir -p /usr/local/share/n98-magerun/modules && cd /usr/local/share/n98-magerun/modules \
     && git clone https://github.com/peterjaap/magerun-addons.git pj-addons
-
-ENV COMPOSER_ALLOW_SUPERUSER 1
 
 COPY conf.d/php.ini /usr/local/etc/php/php.ini
 COPY conf.d/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-zxdebug.ini
